language: go
go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
install:
  - go get -u github.com/golang/dep/cmd/dep
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - dep ensure
  - go test -coverprofile=c.out ./...
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
